language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=">=1.4,<1.5"
  - DJANGO=">=1.5,<1.6"
  - DJANGO=">=1.6,<1.7"
  - DJANGO=">=1.7,<1.8"
  - DJANGO=">=1.8,<1.9"
  - DJANGO=">=1.9a1,<1.10"

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO=">=1.4,<1.5"
  - python: "3.5"
    env: DJANGO=">=1.5,<1.6"
  - python: "3.5"
    env: DJANGO=">=1.6,<1.7"
  - python: "3.5"
    env: DJANGO=">=1.7,<1.8"
  - python: "3.5"
    env: DJANGO=">=1.8,<1.9"

  - python: "3.4"
    env: DJANGO=">=1.4,<1.5"
  - python: "3.4"
    env: DJANGO=">=1.9a1,<1.10"

  - python: "3.3"
    env: DJANGO=">=1.4,<1.5"
  - python: "3.3"
    env: DJANGO=">=1.9a1,<1.10"

  - python: "3.2"
    env: DJANGO=">=1.4,<1.5"
  - python: "3.2"
    env: DJANGO=">=1.9a1,<1.10"

  - python: "2.6"
    env: DJANGO=">=1.7,<1.8"
  - python: "2.6"
    env: DJANGO=">=1.8,<1.9"
  - python: "2.6"
    env: DJANGO=">=1.9a1,<1.10"

install:
  - pip install django$DJANGO coverage==3.6

script:
  - coverage run --source=polymorphic runtests.py
  - coverage report -m

after_success:
  - pip install coveralls==0.2
  - coveralls

branches:
  only:
    - master
